# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 762, 712))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(back.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("back.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 80, 151, 71))
        self.widget.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:18px;\n"
"")
        self.widget.setObjectName("widget")
        self.ubu = QtWidgets.QRadioButton(self.widget)
        self.ubu.setGeometry(QtCore.QRect(20, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.ubu.setFont(font)
        self.ubu.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(211, 211, 211);")
        self.ubu.setObjectName("ubu")
        self.win = QtWidgets.QRadioButton(self.widget)
        self.win.setGeometry(QtCore.QRect(20, 10, 111, 18))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.win.setFont(font)
        self.win.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(211, 211, 211);")
        self.win.setObjectName("win")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(240, 240, 240);")
        self.label_2.setObjectName("label_2")
        self.level = QtWidgets.QComboBox(self.centralwidget)
        self.level.setGeometry(QtCore.QRect(320, 100, 91, 21))
        self.level.setStyleSheet("border-color:rgb(255,255,255);\n"
"color: rgb(214, 214, 214);\n"
"border-radius:6px;\n"
"background-color:rgba(0,0,0,100);")
        self.level.setObjectName("level")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 70, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_6.setObjectName("label_6")
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(20, 170, 441, 241))
        self.result.setStyleSheet("")
        self.result.setObjectName("result")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 120, 75, 23))
        self.pushButton.clicked.connect(self.run)
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def run(self):
        try:
            if self.win.isChecked():  
                os_choice = "Windows 11"
            elif self.ubu.isChecked():
                os_choice = "Ubuntu"
            else:
                self.result.setPlainText("❌ Please select an operating system.")
                return
            level = self.level.currentText()  # adjust name of combobox
            script_path = None

        # Map selections to script paths
            if os_choice == "Windows 11":
                if "L1" in level:
                    self.result.setText('in if')
                    script_path = r"D:\harsha_vardhan\projects\Audit_script\Audit_script_l1.ps1"
                elif "L2" in level:
                    script_path = r"E:\Audit_Script\Windows_11\Audit_Level2.ps1"
                elif "L3" in level:
                    script_path = r"E:\Audit_Script\Windows_11\Audit_Level3.ps1"
            elif os_choice == "Ubuntu":
                if "L1" in level:
                    script_path = r"/home/username/Audit_Script/Ubuntu/Audit_Level1.sh"
                elif "L2" in level:
                    script_path = r"/home/username/Audit_Script/Ubuntu/Audit_Level2.sh"
                elif "L3" in level:
                    script_path = r"/home/username/Audit_Script/Ubuntu/Audit_Level3.sh"

            if not script_path:
                self.result.setPlainText("❌ No script mapped for this selection.")
                return

            if os_choice == "Windows 11":
                completed = subprocess.run(
                    ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", "& '" + script_path + "'"],
                    capture_output=True, text=True
                )
                self.result.setText('in output')
                output = completed.stdout if completed.stdout else completed.stderr

            else:
                completed = subprocess.run(
                    ["bash", script_path],
                    capture_output=True, text=True
                )
                output = completed.stdout if completed.stdout else completed.stderr

        
            self.result.setHtml(self.format_output_with_colors(output))

        except Exception as e:
            QMessageBox.critical(self, "Error", str(e))
        
    def format_output_with_colors(self, text):
        colored_lines = []
        for line in text.splitlines(): # Process line by line
            if "FAIL" in line.upper():
                colored_lines.append(f"<span style='color:red; font-weight:bold;'>{line}</span>")
            elif "PASS" in line.upper():
                colored_lines.append(f"<span style='color:green; font-weight:bold;'>{line}</span>")
            elif "N/A" in line.upper() or "MANUAL" in line.upper():
                colored_lines.append(f"<span style='color:orange; font-weight:bold;'>{line}</span>")
            else:
                colored_lines.append(line)
        return "<br>".join(colored_lines) # Join with HTML line breaks

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ubu.setText(_translate("MainWindow", "Ubuntu"))
        self.win.setText(_translate("MainWindow", "Windows 11"))
        self.label_2.setText(_translate("MainWindow", "Operating System"))
        self.level.setItemText(0, _translate("MainWindow", "L1 - Basic"))
        self.level.setItemText(1, _translate("MainWindow", "L2 - Medium"))
        self.level.setItemText(2, _translate("MainWindow", "L3 - Strict"))
        self.label_6.setText(_translate("MainWindow", "Security Level"))
        self.pushButton.setText(_translate("MainWindow", "Start Audit"))
        self.label_3.setText(_translate("MainWindow", "Audit Script for Windows 11 and Ubuntu "))



if __name__ == "__main__":
    import sys
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
