# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 961, 561))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(:/newPrefix/C:/Users/Revanth Aradya u/Downloads/Gemini_Generated_Image_7sgnwu7sgnwu7sgn.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/C:/Users/Revanth Aradya u/Downloads/Gemini_Generated_Image_fr7qk2fr7qk2fr7q.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 80, 151, 71))
        self.widget.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:18px;\n"
"")
        self.widget.setObjectName("widget")
        self.ubu = QtWidgets.QRadioButton(self.widget)
        self.ubu.setGeometry(QtCore.QRect(20, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.ubu.setFont(font)
        self.ubu.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(211, 211, 211);")
        self.ubu.setObjectName("ubu")
        self.win = QtWidgets.QRadioButton(self.widget)
        self.win.setGeometry(QtCore.QRect(20, 10, 111, 18))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.win.setFont(font)
        self.win.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(211, 211, 211);")
        self.win.setObjectName("win")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(240, 240, 240);")
        self.label_2.setObjectName("label_2")
        self.level = QtWidgets.QComboBox(self.centralwidget)
        self.level.setGeometry(QtCore.QRect(320, 100, 91, 21))
        self.level.setStyleSheet("border-color:rgb(255,255,255);\n"
"color: rgb(214, 214, 214);\n"
"border-radius:6px;\n"
"background-color:rgba(0,0,0,100);")
        self.level.setObjectName("level")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 70, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_6.setObjectName("label_6")
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(30, 190, 441, 241))
        self.result.setStyleSheet("")
        self.result.setObjectName("result")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ubu.setText(_translate("MainWindow", "Ubuntu"))
        self.win.setText(_translate("MainWindow", "Windows 11"))
        self.label_2.setText(_translate("MainWindow", "Operating System"))
        self.level.setItemText(0, _translate("MainWindow", "L1 - Basic"))
        self.level.setItemText(1, _translate("MainWindow", "L2 - Medium"))
        self.level.setItemText(2, _translate("MainWindow", "L3 - Strict"))
        self.label_6.setText(_translate("MainWindow", "Security Level"))
        self.pushButton.setText(_translate("MainWindow", "Start Audit"))
        self.label_3.setText(_translate("MainWindow", "Audit Script for Windows 11 and Ubuntu "))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
